plugins {
    id 'java'
}

group = 'com.zs'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
jar {
    manifest {
        attributes('Main-Class': 'com.zs.assignment5.Main')
    }
}

tasks.register('runAssignment5', JavaExec) {
    group = 'execution'
    description = 'Run Assignment 5 - Git Log Parser'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.zs.assignment5.Main'
    args = ['src/main/resources/log.txt', '2026-02-20']
}
