plugins {
    id 'java'
    id 'application'
}

group = 'com.zs'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    // Add any dependencies here if needed
}

application {
    mainClass = 'com.zs.assignment4.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

compileJava {
    options.encoding = 'UTF-8'
}
