spring.application.name=DemoApp

# Import the custom db.properties file
spring.config.import=classpath:db.properties

# Map custom properties to Spring Datasource properties
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable Hibernate DDL for JPA entity-backed schema management
spring.jpa.hibernate.ddl-auto=update

# Application Port
server.port=8080