package com.zs.assignment10;

import com.zs.assignment10.dao.ProductDao;
import com.zs.assignment10.dao.ProductDaoJdbcImpl;
import com.zs.assignment10.model.Product;
import com.zs.assignment10.util.DatabaseManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The type Product dao jdbc impl test.
 */
class ProductDaoJdbcImplTest {

    private ProductDao productDao;

    /**
     * Sets up.
     *
     * @throws Exception the exception
     */
    @BeforeEach
    void setUp() throws Exception {
        productDao = new ProductDaoJdbcImpl();

        // 1. Clean the database before each test to ensure a predictable state
        try (Connection conn = DatabaseManager.getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.execute("TRUNCATE TABLE products RESTART IDENTITY CASCADE;");

            // 2. Insert baseline test data
            stmt.execute("INSERT INTO products (name, price) VALUES ('Laptop', 1200.00)");
            stmt.execute("INSERT INTO products (name, price) VALUES ('Mouse', 25.50)");
        }
    }

    /**
     * Find all returns all products.
     */
    @Test
    void findAll_ReturnsAllProducts() {
        List<Product> products = productDao.findAll();
        assertEquals(2, products.size());
    }

    /**
     * Find by id valid id returns product.
     */
    @Test
    void findById_ValidId_ReturnsProduct() {
        // ID 1 is the Laptop due to RESTART IDENTITY in setup
        //ID 2 is the Mouse
        Product product1 = productDao.findById(1);
        Product product2=productDao.findById(2);

        assertNotNull(product1);
        assertNotNull(product2);

        assertEquals("Laptop", product1.getName());
        assertEquals(1200.00, product1.getPrice());
        assertEquals("Mouse", product2.getName());
        assertEquals(25.50, product2.getPrice());
    }

    /**
     * Save new product inserts into database.
     */
    @Test
    void save_NewProduct_InsertsIntoDatabase() {
        Product newProduct = new Product(null, "Keyboard", 75.00);
        Product savedProduct = productDao.save(newProduct);

        assertNotNull(savedProduct.getId()); // ID should be generated by Postgres
        assertTrue(productDao.exists(savedProduct.getId()));
    }

    /**
     * Updating existing product updates database.
     */
    @Test
    void updating_ExistingProduct_UpdatesDatabase() {
        Product existingProduct = productDao.findById(1);
        existingProduct.setId(1); // Modifying the Laptop
        Product updatedProduct = new Product(1, "Gaming Laptop", 1500.00);

        productDao.save(updatedProduct);

        Product fetchedProduct = productDao.findById(1);

        assertEquals(1,fetchedProduct.getId());
        assertEquals("Gaming Laptop", fetchedProduct.getName());
        assertEquals(1500.00, fetchedProduct.getPrice());
    }

    /**
     * Delete by id valid id removed from database.
     */
    @Test
    void deleteById_ValidId_RemovedFromDatabase() {
        assertTrue(productDao.exists(2)); // Mouse exists

        productDao.deleteById(2);

        assertFalse(productDao.exists(2));
    }

    /**
     * Delete by id invalid id not removed from database.
     */
    @Test
    void deleteById_InvalidId_NotRemovedFromDatabase() {
        assertFalse(productDao.exists(999)); // Non-existent ID

        boolean result = productDao.deleteById(999);

        assertFalse(result); // Should return false since it doesn't exist
    }
}
